### ISSUE TITLE
Sign disappearing after server reboot

### ISSUE THREAD

**Issue by Uboaaaaa** [StylexTV/GSigns#12] opened 2020-10-08 11:23 UTC
**Version**: minecraft 1.16.3, paper #211, plugin version 5.2
**_Symptoms_**: 
After server reboot, the image on the board disappears, leaving an empty item frame behind. The empty item frame can be removed using /gsign remove command but will be back after another reboot. The item frame is of normal size (without map), not enlarged ones (slotted with map).

Others have told me that they've encountered the same issue where the sign disappears once they are out of sight. Both of us have multiverse installed.

**Comment by stylextv** [comment] 2020-10-10 08:23
You are saying that you created a new sign, which worked well, but after typing "/reload confirm" the item frames are empty?
Then you delete the sign using "/gs remove" and do the item frames acctually get removed? Do you get the "The sign has been removed" message? After that you say that after another restart the item frames are magically there again? Have you checked the console, because it will tell you "Succesfully loaded n item-frames in x seconds.". Does it still say that it "Succesfully loaded" your item frames or does it say that it loaded 0?

**Comment by ghost** [comment] 2020-10-10 08:43
So as soon as I create a G-Sign and fly out of range and come back immediately it is still there. But as soon as I fly out of range and stay away a bit longer and come back it is gone and only empty frames are visible.

**Comment by ghost** [comment] 2020-10-10 08:45
But if I take the server offline and restart it again the sign is there again until I repeat the above steps where it disappears again.

**Comment by ghost** [comment] 2020-10-10 09:05
And what is very important is that you have to be very far away from the signs, wait a while and then go back to not show them again. If I am only a short distance away and go back they stay there.

**Comment by Uboaaaaa** [comment] 2020-10-10 09:31
I'll set up a local server to do further testing. I'm very glad to help with this issue.

**Comment by Uboaaaaa** [comment] 2020-10-10 10:41
I managed to reproduce it on git-Paper-220 (MC: 1.16.3), which is the version I encountered the issue. The only plugin I installed is G-signs.

**Procedure:**
I created a gamemode sign.
![2020-10-10_11 12 07](https://user-images.githubusercontent.com/70588463/95652604-3b648300-0aea-11eb-98a5-78339e3ece73.png)
I then restarted my server.
The console outputs the following.
![console1](https://user-images.githubusercontent.com/70588463/95652616-546d3400-0aea-11eb-95b5-debdff24ba76.jpg)
The image isn't shown.
![2020-10-10_11 14 47](https://user-images.githubusercontent.com/70588463/95653186-9d26ec00-0aee-11eb-9db3-38e294a1dbb4.png)


**However**, after I type **/reload confirm** which reloads the server, **the images shows themselves**.
I don't use that command on my production server, all I used is /stop.

Regarding my operation on the empty item frames, I used **/gs remove** and punched the item frame. It disappeared with some funny behaviour:
- In creative mode I also breaks the block behind it.
- In survival mode the frame drop as item. There's no sound being played.

In either way I don't think the plugin has registered that. After I do /reload confirm the images returns. And if I restart the server, empty item frames returns.

**Comment by Uboaaaaa** [comment] 2020-10-10 10:46
I wasn't able to reproduce @blakedj012 's issue unfortunately. I flew miles away but the images are still there when I return. :(

**Comment by stylextv** [comment] 2020-10-10 12:10
For some weird reason I can't reproduce the issue you mentioned. When creating a sign, then typing /stop, starting the server and rejoining, the sign is still there, with the image.

**Comment by Uboaaaaa** [comment] 2020-10-10 13:05
Hmmm... May I ask how you created the sign? Using an image link or using files in the plugin folder? 
I did the later one and wondering whether that's the difference

**Comment by stylextv** [comment] 2020-10-10 13:10
> Hmmm... May I ask how you created the sign? Using an image link or using files in the plugin folder?
> I did the later one and wondering whether that's the difference

Well I just created an empty sign using: /gs create {}

**Comment by stylextv** [comment] 2020-10-10 13:10
Doing more testing later...

**Comment by stylextv** [comment] 2020-10-14 11:42
Should be fixed in the latest version.
Let me know if it wasn't tho

**Closed as completed by stylextv** 2020-10-14 11:42 UTC
Labels: bug
